Resource group added
IBM-Cloud/multiple-environments-as-code pull request #1
Opened 2018-10-17 08:14 UTC by VidyasagarMSC

2018-10-24 06:41 UTC, l2fprod requested changes

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/development.tfvars.tmpl
> +resource_quota = ""
can we suggest a good default?

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/development.tfvars.tmpl
> +cloudantnosqldb_plan = ""
Can we put a default value and in the comment show the possible values?

```suggestion
# Plan for Cloudant database: lite or standard
cloudantnosqldb_plan = "lite"
```

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/development.tfvars.tmpl
> +cloudobjectstorage_plan = ""
same as for the cloudant plan

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/development.tfvars.tmpl
> +cloudantnosqldb_location = ""
any `ibmcloud` command I could use to find the list of regions?

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/main.tf
> +resource "ibm_resource_instance" "objectstorage" {
maybe move this before the cluster so that the flow is:

- create services
- create cluster
- bind services

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/main.tf
> +data "ibm_resource_quota" "quota" {
this should move close to the resource group creation

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/outputs.tf
> +output "resource_group_id" {
the comment on line 1 does not apply to "output" but to resource. You should comment why you add an "output"

2018-10-24 06:41 UTC, l2fprod commented on terraform/per-environment/main.tf
> +  name              = "${var.environment_name}-cluster"
would be better split between one ibm_container_cluster and one ibm_container_worker_pool, one ibm_container_worker_pool_zone_attachment

these constructs are better than the "worker_num" in the long term

2018-10-24 06:41 UTC, l2fprod commented on terraform/roles/development/development.tfvars.tmpl
> +access_group_name_developer_role = "Example-Developer-Role"
seems that the access group names are the same for all environments? This will not work. I'd say we need access groups to be named something like "<env>-<role>"

2018-10-24 06:41 UTC, l2fprod commented on terraform/roles/development/main.tf
> +resource "ibm_iam_access_group" "developer_role" {
would be good to group all resources for Developer role, then Tester, Operator and Pipeline, otherwise it makes it difficult to read. Also add comments to separate the sections

2018-10-24 06:41 UTC, l2fprod commented on terraform/roles/development/main.tf
> +  roles           = "${var.resource_group_roles_developer}"
why are the roles variables? The example should specify the roles as the shellscripts were doing to map what is the tutorial table

2018-10-24 08:25 UTC, VidyasagarMSC commented on terraform/per-environment/development.tfvars.tmpl
> +cloudantnosqldb_location = ""
```suggestion
ibmcloud catalog service cloudantnosqldb
```

2018-10-24 14:07 UTC, VidyasagarMSC commented on terraform/per-environment/development.tfvars.tmpl
> +resource_quota = ""
Done

2018-10-24 14:08 UTC, VidyasagarMSC commented on terraform/per-environment/development.tfvars.tmpl
> +cloudobjectstorage_plan = ""
Done

2018-10-24 14:08 UTC, VidyasagarMSC commented on terraform/per-environment/main.tf
> +resource "ibm_resource_instance" "objectstorage" {
done

2018-10-24 14:08 UTC, VidyasagarMSC commented on terraform/per-environment/development.tfvars.tmpl
> +cloudantnosqldb_location = ""
Done

2018-10-24 14:08 UTC, VidyasagarMSC commented on terraform/per-environment/outputs.tf
> +output "resource_group_id" {
changed

2018-10-24 14:09 UTC, VidyasagarMSC commented on terraform/per-environment/main.tf
> +  name              = "${var.environment_name}-cluster"
Facing an issue with zone_attachment

2018-10-24 14:09 UTC, VidyasagarMSC commented on terraform/roles/development/development.tfvars.tmpl
> +access_group_name_developer_role = "Example-Developer-Role"
Added respective environment after '-'

2018-10-24 14:10 UTC, VidyasagarMSC commented on terraform/roles/development/main.tf
> +resource "ibm_iam_access_group" "developer_role" {
Done

2018-10-24 14:10 UTC, VidyasagarMSC commented on terraform/roles/development/main.tf
> +  roles           = "${var.resource_group_roles_developer}"
Added for Development and production.
Testing had an issue so removed the access policies as the tester will be using the application to test.

2018-10-25 04:42 UTC, VidyasagarMSC commented on terraform/per-environment/main.tf
> +  name              = "${var.environment_name}-cluster"
This is resolved with a workaround.

2018-10-25 09:23 UTC, merged